import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import Providers from "@/providers";
// import RadioGroup from "@mui/material/RadioGroup";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					`${geistSans.variable} ${geistMono.variable} antialiased`,
					"bg-background text-foreground",
					"px-6 py-20",
					"",
					""
				)}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}

// export default function RootLayout({
// 	children,
// }: Readonly<{
// 	children: React.ReactNode;
// }>) {
// 	return (
// 		<html lang="en">
// 			<body
// 				className={cn(
// 					`${geistSans.variable} ${geistMono.variable} antialiased`,
// 					"bg-background text-foreground",
// 					"px-6 py-20",
// 					"",
// 					""
// 				)}>
// 				{children}
// 			</body>
// 		</html>
// 	);
// }
// // src/app/layout.tsx
