import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";
import Providers from "@/providers/providers";
import ThemeToggle from "@/components/layout/themeToggle";
import StoreHeader from "@/components/layout/header";
import getTopicsServer from "@/utils/getTopicsServer";
import { readTopicsCache, isCacheValid } from "@/utils/topicsCache";

/* TODO [ ]: Add stylized frontpage;
			- add popular pics section
 			- add bookshelf section (kategories)
 			- add subjects section (kategories)
? 			- add previous reads / downloads
			- add add hot / trending (newcommers with many downloads)(algorithm - popular / newest)
?			- add highlighted Authors grid
			- add 
*/
// TODO [ ]: mini-productcard is broken and needs fixing.
// TODO [ ]: book profile layout is broken (again), need fixing (again).
// TODO [ ]: organize components
// TODO [ ]: cleanup tailwind, remove unused components etc
// TODO [ ]: make default book cover using logo, the current one looks bad.
// TODO [ ]: make 'your favorites' show empty when there is no favorites.
// TODO [ ]:
// ! NOTE: the API is not working correctly; cannot combine topics in search.
// ? Suggestion: do a fetch for all the different topics, and then make own algorithm to sort the items contain all topics.

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// Prefer server-side cached full-topic list when available and fresh.
	let topics: string[] = [];
	try {
		const cache = await readTopicsCache();
		if (isCacheValid(cache) && cache?.topics && cache.topics.length > 0) {
			topics = cache.topics;
		} else {
			// Fall back to fetching only first page for fast initial load.
			try {
				topics = await getTopicsServer(1);
			} catch (e) {
				console.error("getTopicsServer error:", e);
				topics = [];
			}
		}
	} catch (e) {
		console.error(
			"RootLayout: cache read failed, falling back to partial fetch",
			e
		);
		try {
			topics = await getTopicsServer(1);
		} catch (err) {
			console.error("getTopicsServer error:", err);
			topics = [];
		}
	}

	return (
		// The hydrationWarnign is due to browser extentions, so I'll disable it before release.
		// TODO: befor release - remove supression.
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					`${geistSans.variable} ${geistMono.variable} antialiased`,
					// "bg-background text-foreground",
					// "h-screen flex flex-col",
					// "max-w-4xl mx-auto",
					// "max-w-5xl mx-auto",
					// "lg:h-screen",
					// "h-fit",
					// "h-full",
					// "max-w-8xl mx-auto",''
					// "scale-x-75",
					// "max-w-xl mx-auto",
					// removed hard max-w & mx-auto from body so app can be full-bleed
					// "max-w-7xl mx-auto",
					// "px-10",
					"max-w-7xl mx-auto",
					"px-10",
					"md:px-10",
					"lg:px-10",
					"min-h-0",
					// "px-10",
					// "xl:px-50",
					// "xl:px-100",
					// "min-h-screen",

					// "min-w-screen",
					// "min-w-0",
					// "w-screen",
					"w-200px",
					// "max-w-7xl mx-auto",
					// "max-w-xl",
					// "min-w-3xs",
					"sm:max-w-7xl",
					// "mx-auto",
					// "px-10",
					"",
					"",
					""
				)}>
				<Providers>
					{/* keep centered constraints here instead of on body */}
					<div className="">
						{/* <div className="max-w-7xl mx-auto px-10"> */}
						<StoreHeader topics={topics} />
						{children}
						<ThemeToggle />
					</div>
				</Providers>
			</body>
		</html>
	);
}
