import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";
import Providers from "@/providers/providers";
import ThemeToggle from "@/components/themeToggle";
import StoreHeader from "@/components/header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					`${geistSans.variable} ${geistMono.variable} antialiased`,
					"bg-background text-foreground",
					"h-screen flex flex-col",
					"max-w-4xl mx-auto",
					"max-w-5xl mx-auto",
					"lg:h-screen",
					"h-fit",
					"h-full",
					"max-w-8xl mx-auto",
					// "px-4 sm:px-6 lg:px-8",
					// "justify-start items-stretch",
					"",
					""
				)}>
				<Providers>
					<StoreHeader />
					{children}
					<ThemeToggle />
				</Providers>
			</body>
		</html>
	);
}
